{
 "title": "Vending Machine",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requested/Watched",
   "type": "singlestat",
   "description": "requested over watched on last 5 minutes",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vending_emoji_requested_total) / sum(vending_emoji_front_watched_total)"
    }
   ]
  },
  {
   "title": "Delivered/Watched",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vending_emoji_delivered_total) / sum(vending_emoji_front_watched_total)"
    }
   ]
  },
  {
   "title": "Feedback received/Watched",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vending_emoji_feedback_received_total) / sum(vending_emoji_front_watched_total)"
    }
   ]
  },
  {
   "title": "Vending machine state",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{app=\"vending\"}"
    }
   ]
  },
  {
   "title": "Visitors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vending_emoji_front_watched_total",
     "legendFormat": "Total visitor"
    },
    {
     "expr": "rate(vending_emoji_front_watched_total[1m])",
     "legendFormat": "Visitors/minute"
    }
   ]
  },
  {
   "title": "Delivered/Requested",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vending_emoji_delivered_total) / sum(vending_emoji_requested_total)"
    }
   ]
  },
  {
   "title": "Feedback received/Delivered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vending_emoji_feedback_received_total) / sum(vending_emoji_delivered_total)"
    }
   ]
  },
  {
   "title": "Overall Satisfaction Index",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vending_emoji_overall_satisfaction_index"
    }
   ]
  },
  {
   "title": "Cooking Emoji Duration (s) Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vending_emoji_cooking_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cooking Emoji Duration (s) Cummulative Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vending_emoji_cooking_duration_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requested Categories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vending_emoji_requested_total) by (category_name)",
     "legendFormat": "{{category_name}}"
    }
   ]
  },
  {
   "title": "Feedback: Emoji likes/dislikes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vending_emoji_feedback_received_total[1m])",
     "legendFormat": "{{feedback}}"
    },
    {
     "expr": "sum(rate(vending_emoji_feedback_received_total[1m]))",
     "legendFormat": "{{feedback}}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{app=\"vending\"}"
    }
   ]
  },
  {
   "title": "Feedback Type Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vending_emoji_feedback_received_total) by (feedback)",
     "legendFormat": "{{feedback}}"
    }
   ]
  }
 ]
}