---
global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 30s
scrape_configs:
  - job_name: machine
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node_exporter:9100'
        labels:
          milabel: exporter
  - job_name: grafana
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'grafana:3000'
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: vending-app
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'server:8080'
        labels:
          app: vending
